# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca53f74206f6ef8d9b9be082f74c8db36ed064c06ef62275d426b3ef6b8c6e7d530cdeadd940cece767d81e84debe7c1b1d1e6dcb8194747c767eed15ff81faf
  twilio_client_id: <%= ENV["ACCOUNT SID"] %>
  twilio_auth_token: <%= ENV["AUTH TOKEN"] %>
  twilio_phone_number: <%= ENV["PHONE NUMBER"] %>
  twilio_test_number: <%= ENV["TEST NUMBER"] %>

test:
  secret_key_base: edba934d0b8201ce416125c570fb65b922087029b9e01ca38b62f1cc863681f3a1c609655e2feba312e82c266f1992277bbcd74533d878e3b6bf25f67960c4b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_client_id: <%= ENV["ACCOUNT SID"] %>
  twilio_auth_token: <%= ENV["AUTH TOKEN"] %>
  twilio_phone_number: <%= ENV["PHONE NUMBER"] %>
  twilio_test_number: <%= ENV["TEST NUMBER"] %>
